import jsPDF from 'jspdf';
import { BrandDiscovery, BrandStrategy, LogoAssistantData } from '../types';

/**
 * Polymorphic PDF Service
 * Handles high-fidelity PDF generation for all BrandForge tools.
 * Uses the Translation Pattern to map tool-specific data to a shared layout engine.
 */

interface PDFOptions {
  brandName: string;
  filename: string;
}

class PDFLayoutEngine {
  doc: jsPDF;
  margin: number = 50;
  contentWidth: number;
  pageWidth: number;
  pageHeight: number;
  y: number;
  headerHeight: number = 35;
  footerHeight: number = 30;
  contentTop: number;

  constructor(options: PDFOptions) {
    this.doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
    this.pageWidth = this.doc.internal.pageSize.getWidth();
    this.pageHeight = this.doc.internal.pageSize.getHeight();
    this.contentWidth = this.pageWidth - this.margin * 2;
    this.contentTop = this.margin + this.headerHeight;
    this.y = this.margin;
    this.brandName = options.brandName;
  }

  brandName: string;

  addHeaderFooter() {
    const doc = this.doc;
    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(this.brandName.toUpperCase(), this.margin, this.margin - 5);
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.setLineWidth(0.5);
    doc.line(this.margin, this.margin + 5, this.pageWidth - this.margin, this.margin + 5);

    // Footer
    const pageNum = (doc as any).internal.getCurrentPageInfo().pageNumber;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by BrandForge Ultimate Branding Suite', this.margin, this.pageHeight - 25);
    doc.text(`Page ${pageNum}`, this.pageWidth - this.margin, this.pageHeight - 25, { align: 'right' });
    doc.line(this.margin, this.pageHeight - 35, this.pageWidth - this.margin, this.pageHeight - 35);
  }

  checkPage(needed: number) {
    if (this.y + needed > this.pageHeight - this.margin - this.footerHeight) {
      this.doc.addPage();
      this.addHeaderFooter();
      this.y = this.contentTop;
    }
  }

  addTitle(text: string) {
    this.checkPage(40);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(22);
    this.doc.setTextColor(30, 41, 59); // slate-800
    this.doc.text(text, this.margin, this.y);
    this.y += 32;
  }

  addSubtitle(text: string) {
    this.checkPage(25);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(11);
    this.doc.setTextColor(37, 99, 235); // brand-blue
    this.doc.text(text.toUpperCase(), this.margin, this.y);
    this.y += 18;
  }

  addBody(text: string | null | undefined) {
    if (!text) return;
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(10);
    this.doc.setTextColor(71, 85, 105); // slate-600
    const lines = this.doc.splitTextToSize(text, this.contentWidth);
    for (const line of lines) {
      this.checkPage(14);
      this.doc.text(line, this.margin, this.y);
      this.y += 14;
    }
    this.y += 6;
  }

  addBullet(label: string, value: string | null | undefined) {
    if (!value) return;
    this.checkPage(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(10);
    this.doc.setTextColor(30, 41, 59);
    this.doc.text(`• ${label}:`, this.margin, this.y);
    
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(71, 85, 105);
    const xOffset = this.doc.getTextWidth(`• ${label}: `);
    const availableWidth = this.contentWidth - xOffset;
    const lines = this.doc.splitTextToSize(value, availableWidth);
    
    for (let i = 0; i < lines.length; i++) {
      if (i > 0) {
        this.checkPage(14);
        this.doc.text(lines[i], this.margin + xOffset, this.y);
      } else {
        this.doc.text(lines[i], this.margin + xOffset, this.y);
      }
      this.y += 14;
    }
  }

  addDivider() {
    this.checkPage(30);
    this.y += 10;
    this.doc.setDrawColor(241, 245, 249); // slate-100
    this.doc.line(this.margin, this.y, this.pageWidth - this.margin, this.y);
    this.y += 24;
  }

  save(filename: string) {
    this.doc.save(filename);
  }
}

export const pdfService = {
  /**
   * Export Brand Strategy PDF
   */
  exportStrategy: (strategy: BrandStrategy, brandName: string) => {
    const engine = new PDFLayoutEngine({
      brandName: brandName || 'Brand Strategy',
      filename: `${(brandName || 'Brand').replace(/\s+/g, '_')}_Strategy_Blueprint.pdf`
    });

    const { doc } = engine;

    // --- COVER PAGE ---
    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(3);
    doc.line(engine.margin, 80, engine.pageWidth - engine.margin, 80);

    engine.y = engine.pageHeight * 0.35;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(32);
    doc.setTextColor(30, 41, 59);
    const titleLines = doc.splitTextToSize(engine.brandName, engine.contentWidth);
    titleLines.forEach((line: string) => {
      doc.text(line, engine.pageWidth / 2, engine.y, { align: 'center' });
      engine.y += 40;
    });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.setTextColor(100, 116, 139);
    doc.text('Strategic Brand Blueprint', engine.pageWidth / 2, engine.y, { align: 'center' });
    
    engine.y += 100;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('PREPARED BY', engine.pageWidth / 2, engine.y, { align: 'center' });
    engine.y += 16;
    doc.setFont('helvetica', 'normal');
    doc.text('BrandForge Intelligence Engine', engine.pageWidth / 2, engine.y, { align: 'center' });
    engine.y += 24;
    doc.text(new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }), engine.pageWidth / 2, engine.y, { align: 'center' });

    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(3);
    doc.line(engine.margin, engine.pageHeight - 80, engine.pageWidth - engine.margin, engine.pageHeight - 80);

    // --- CONTENT ---
    doc.addPage();
    engine.addHeaderFooter();
    engine.y = engine.contentTop;

    engine.addTitle('Executive Overview');
    engine.addBody(strategy.overview?.whoWeAre);
    engine.addSubtitle('Core Intent');
    engine.addBody(strategy.overview?.whatWeDo);
    engine.addSubtitle('Operational Strategy');
    engine.addBody(strategy.overview?.howWeDoIt);
    
    engine.addDivider();
    engine.addTitle('Brand Soul');
    engine.addSubtitle('Mission');
    engine.addBody(strategy.foundation?.mission);
    engine.addSubtitle('Vision');
    engine.addBody(strategy.foundation?.vision);
    engine.addSubtitle('Philosophy');
    engine.addBody(strategy.foundation?.philosophy);

    // FIX: Core Values Mapping
    if (strategy.values && strategy.values.length > 0) {
      engine.addSubtitle('Core Values');
      strategy.values.forEach(v => {
        engine.addBullet(v.name, v.description);
      });
      engine.y += 10;
    }

    engine.addDivider();
    engine.addTitle('Psychological Profile');
    
    // Primary Archetype
    engine.addSubtitle(`Primary Archetype: ${strategy.archetype?.primary?.name}`);
    engine.addBody(strategy.archetype?.primary?.personalityNarrative);
    
    if (strategy.archetype?.primary?.traits) {
      engine.addSubtitle('Core Traits');
      engine.addBody(strategy.archetype.primary.traits.join(' • '));
    }
    
    engine.addSubtitle('Strategic Rationale');
    engine.addBody(strategy.archetype?.primary?.strategicRationale);
    
    // Secondary Archetype
    if (strategy.archetype?.secondary) {
      engine.addSubtitle(`Secondary/Support: ${strategy.archetype.secondary.name}`);
      engine.addBody(strategy.archetype.secondary.personalityNarrative || strategy.archetype.secondary.description);
    }

    engine.addDivider();
    engine.addTitle('Tone of Voice Framework');
    engine.addSubtitle('Voice Essence');
    engine.addBody(strategy.archetype?.behavior?.tone?.framework);
    engine.addSubtitle('Voice Description');
    engine.addBody(strategy.archetype?.behavior?.tone?.description);
    
    if (strategy.archetype?.behavior?.tone?.examples) {
      engine.addSubtitle('Voice Examples');
      strategy.archetype.behavior.tone.examples.forEach(ex => engine.addBullet('Example', ex));
    }

    engine.addDivider();
    engine.addTitle('Market Positioning');
    engine.addSubtitle('Competitive Statement');
    engine.addBody(strategy.marketPosition?.statement);
    engine.addSubtitle('Market Gap Analysis');
    engine.addBody(strategy.marketPosition?.analysis);
    
    if (strategy.touchPoints && strategy.touchPoints.length > 0) {
      engine.addSubtitle('Brand Touchpoints');
      strategy.touchPoints.forEach(tp => {
        engine.addBullet(tp.category, tp.items.join(', '));
      });
    }

    engine.addDivider();
    engine.addTitle('Messaging & Narrative');
    engine.addSubtitle('The Big Idea');
    engine.addBody(strategy.coreIdea);
    engine.addSubtitle('Core Brand Narrative');
    engine.addBody(strategy.story);
    
    if (strategy.messaging?.coreMessage) {
      engine.addSubtitle('Core Message');
      engine.addBody(strategy.messaging.coreMessage);
    }

    engine.addDivider();
    engine.addTitle('Growth & Evolution');
    
    if (strategy.growthPrograms && strategy.growthPrograms.length > 0) {
      engine.addSubtitle('Growth Programs');
      strategy.growthPrograms.forEach(gp => engine.addBullet(gp.name, gp.description));
    }
    
    if (strategy.partnerships && strategy.partnerships.length > 0) {
      engine.addSubtitle('Strategic Partnerships');
      strategy.partnerships.forEach(sp => engine.addBullet(sp.name, sp.description));
    }

    if (strategy.experienceDesign) {
      engine.addSubtitle('Design Experience');
      engine.addBody(strategy.experienceDesign);
    }

    engine.save(`${(engine.brandName || 'Brand').replace(/\s+/g, '_')}_Strategy_Blueprint.pdf`);
  },

  /**
   * Export Brand Discovery PDF
   */
  exportDiscovery: (discovery: BrandDiscovery, brandName: string) => {
    const engine = new PDFLayoutEngine({
      brandName: brandName || discovery.registeredName || 'Brand Discovery',
      filename: `${(brandName || discovery.registeredName || 'Brand').replace(/\s+/g, '_')}_Discovery_Blueprint.pdf`
    });

    const { doc } = engine;

    // --- COVER PAGE ---
    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(3);
    doc.line(engine.margin, 80, engine.pageWidth - engine.margin, 80);

    engine.y = engine.pageHeight * 0.35;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(32);
    doc.setTextColor(30, 41, 59);
    const titleLines = doc.splitTextToSize(engine.brandName, engine.contentWidth);
    titleLines.forEach((line: string) => {
      doc.text(line, engine.pageWidth / 2, engine.y, { align: 'center' });
      engine.y += 40;
    });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.setTextColor(100, 116, 139);
    doc.text('Brand Discovery Blueprint', engine.pageWidth / 2, engine.y, { align: 'center' });
    
    engine.y += 100;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('PREPARED BY', engine.pageWidth / 2, engine.y, { align: 'center' });
    engine.y += 16;
    doc.setFont('helvetica', 'normal');
    doc.text('BrandForge Intelligence Engine', engine.pageWidth / 2, engine.y, { align: 'center' });
    engine.y += 24;
    doc.text(new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }), engine.pageWidth / 2, engine.y, { align: 'center' });

    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(3);
    doc.line(engine.margin, engine.pageHeight - 80, engine.pageWidth - engine.margin, engine.pageHeight - 80);

    // --- CONTENT ---
    doc.addPage();
    engine.addHeaderFooter();
    engine.y = engine.contentTop;

    engine.addTitle('Project Foundation');
    engine.addBullet('Registered Name', discovery.registeredName);
    engine.addBullet('Industry', discovery.industry);
    engine.addBullet('Business Stage', discovery.stage);
    engine.addBullet('Target Audience', discovery.idealCustomers);
    
    engine.addDivider();
    engine.addTitle('Core Philosophy');
    engine.addSubtitle('Mission Statement');
    engine.addBody(discovery.mission);
    engine.addSubtitle('Vision Statement');
    engine.addBody(discovery.vision);
    engine.addSubtitle('Operating Philosophy');
    engine.addBody(discovery.philosophy);

    engine.addDivider();
    engine.addTitle('Problem & Solution');
    engine.addSubtitle('The Problem');
    engine.addBody(discovery.problemSolving);
    engine.addSubtitle('The Solution');
    engine.addBody(discovery.productsServices);
    engine.addSubtitle('Unique Differentiation');
    engine.addBody(discovery.differentiation);

    engine.addDivider();
    engine.addTitle('Strategic Attributes');
    engine.addBullet('Core Values', (discovery.coreValues || []).join(', '));
    engine.addBullet('Brand Strengths', (discovery.strengths || []).join(', '));
    engine.addBullet('Market Benefits', (discovery.customerBenefits || []).join(', '));
    engine.addBullet('Emotional Outcomes', (discovery.customerEmotionalOutcome || []).join(', '));
    engine.addBullet('Brand Feel', (discovery.brandFeel || []).join(', '));

    engine.save(`${(engine.brandName || 'Brand').replace(/\s+/g, '_')}_Discovery_Blueprint.pdf`);
  },

  /**
   * Export Logo Strategy PDF
   */
  exportLogo: (data: LogoAssistantData, discovery: BrandDiscovery, brandName: string) => {
    const engine = new PDFLayoutEngine({
      brandName: brandName || discovery.brandNameLogo || discovery.registeredName || 'BrandForge Project',
      filename: `${(brandName || discovery.brandNameLogo || discovery.registeredName || 'Brand').replace(/\s+/g, '_')}_Logo_Strategy.pdf`
    });

    const { doc } = engine;

    // --- COVER PAGE ---
    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(3);
    doc.line(engine.margin, 80, engine.pageWidth - engine.margin, 80);

    engine.y = engine.pageHeight * 0.35;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(32);
    doc.setTextColor(30, 41, 59);
    const titleLines = doc.splitTextToSize(engine.brandName, engine.contentWidth);
    titleLines.forEach((line: string) => {
      doc.text(line, engine.pageWidth / 2, engine.y, { align: 'center' });
      engine.y += 40;
    });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.setTextColor(100, 116, 139);
    doc.text('Logo Strategy Blueprint', engine.pageWidth / 2, engine.y, { align: 'center' });
    
    engine.y += 100;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('PREPARED BY', engine.pageWidth / 2, engine.y, { align: 'center' });
    engine.y += 16;
    doc.setFont('helvetica', 'normal');
    doc.text('BrandForge Intelligence Engine', engine.pageWidth / 2, engine.y, { align: 'center' });
    engine.y += 24;
    doc.text(new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }), engine.pageWidth / 2, engine.y, { align: 'center' });

    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(3);
    doc.line(engine.margin, engine.pageHeight - 80, engine.pageWidth - engine.margin, engine.pageHeight - 80);

    // --- CONTENT ---
    doc.addPage();
    engine.addHeaderFooter();
    engine.y = engine.contentTop;

    engine.addTitle('The Brand Noun Toolkit');
    engine.addBody('A collection of 50 name-ready constructs and visual anchors categorized by linguistic territory.');
    engine.y += 10;

    const categories = [
      { label: 'Real Words', items: data.nouns.realWords },
      { label: 'Invented Words', items: data.nouns.inventedWords },
      { label: 'Compound Words', items: data.nouns.compoundWords },
      { label: 'Metaphorical Nouns', items: data.nouns.metaphoricalNouns },
      { label: 'Abstract Constructs', items: data.nouns.abstractConstructs }
    ];

    categories.forEach(cat => {
      if (cat.items.length > 0) {
        engine.addSubtitle(cat.label);
        cat.items.forEach(item => {
          const noun = typeof item === 'string' ? { word: item, anchor: '', territory: '' } : item;
          const label = noun.territory && noun.territory !== 'Normal' 
            ? `${noun.word} (${noun.territory})` 
            : noun.word;
          
          if (noun.anchor) {
            engine.addBullet(label, noun.anchor);
          } else {
            engine.addBody(noun.word);
          }
        });
        engine.y += 10;
      }
    });

    engine.addDivider();
    engine.addTitle('Strategic Directions');
    engine.addBody('Three expansive visual rationales tailored to the brand spirit and archetype.');
    engine.y += 10;

    data.concepts.forEach((concept, i) => {
      engine.addSubtitle(`Direction 0${i + 1}`);
      engine.addBody(concept);
      engine.y += 10;
    });

    if (data.smushes.length > 0) {
      engine.addDivider();
      engine.addTitle('Concept Smush Pairings');
      engine.addBody('Clever visual pairings synthesized from the toolkit to create unique, memorable identity marks.');
      engine.y += 10;

      data.smushes.forEach((smush) => {
        engine.checkPage(40);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(30, 41, 59);
        doc.text(`${smush.pair[0]} + ${smush.pair[1]}`, engine.margin, engine.y);
        engine.y += 16;
        engine.addBody(smush.description);
        engine.y += 8;
      });
    }

    if (data.variations.length > 0) {
      engine.addDivider();
      engine.addTitle('Adaptive Identity System');
      engine.addBody('Essential logo lockups and functional touchpoints defined for professional brand handoff.');
      engine.y += 10;

      data.variations.forEach(v => {
        const [title, rationale] = v.split(':');
        engine.addSubtitle(title.trim());
        engine.addBody(rationale?.trim() || '');
        engine.y += 8;
      });
    }

    engine.save(`${(engine.brandName || 'Brand').replace(/\s+/g, '_')}_Logo_Strategy.pdf`);
  }
};
