import React, { useEffect, useState } from 'react';
import { BrandDiscovery, BrandSystem, BrandStrategy, AppNotification } from '../types';
import { Card, Button } from './UI';
import { brandService } from '../services/brandService';
import ReactMarkdown from 'react-markdown';
import { FileText, Download, Loader2, CheckCircle2, Copy, Check } from 'lucide-react';

interface Props {
  discovery: BrandDiscovery;
  strategy: BrandStrategy;
  system: BrandSystem;
  addNotification: (n: Omit<AppNotification, 'id' | 'timestamp' | 'read'>) => Promise<void>;
}

export const UsageGuideGenerator = ({ discovery, strategy, system, addNotification }: Props) => {
  const [guide, setGuide] = useState('');
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const generate = async () => {
      try {
        const text = await brandService.generateUsageGuide(discovery, strategy, system);
        setGuide(text);
        addNotification({
          title: 'Brand Guide Ready',
          type: 'success',
          message: `Comprehensive documentation for ${discovery.brandNameLogo || discovery.name} has been synthesized.`
        });
      } catch (err: any) {
        addNotification({
          title: 'Guide Generation Failed',
          type: 'error',
          message: err.message || 'The AI was unable to generate your brand usage guide.'
        });
      } finally {
        setLoading(false);
      }
    };
    generate();
  }, [discovery, strategy, system]);

  const downloadGuide = () => {
    const filename = `${(discovery.brandNameLogo || discovery.name || 'Brand').replace(/\s+/g, '_')}_Brand_Guide.md`;
    const blob = new Blob([guide], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    
    addNotification({
      title: 'Documentation Exported',
      type: 'success',
      message: `Successfully downloaded ${filename} to your local machine.`
    });
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(guide);
    setCopied(true);
    addNotification({
      title: 'Copied to Clipboard',
      type: 'info',
      message: 'Brand guide markdown has been copied for external use.'
    });
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] space-y-4">
        <Loader2 className="w-12 h-12 text-brand-600 animate-spin" />
        <p className="text-slate-500 font-medium">Crafting your professional brand guide...</p>
      </div>
    );
  }

  return (
    <div className="max-w-none mx-auto space-y-[var(--space-section)]">
      <div className="text-center space-y-[var(--space-gap)]">
        <div className="space-y-[var(--space-item)]">
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900">Brand Usage Guide</h2>
          <p className="text-sm sm:text-base text-slate-500">Your comprehensive brand documentation is ready.</p>
        </div>
        
        <div className="flex items-center justify-center gap-2 sm:gap-4">
          <Button variant="secondary" onClick={copyToClipboard} size="md" className="gap-2 px-6">
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied!' : 'Copy Markdown'}
          </Button>
          <Button onClick={downloadGuide} size="md" className="gap-2 px-6">
            <Download className="w-4 h-4" />
            Download .md
          </Button>
        </div>
      </div>

      <Card className="p-0 overflow-hidden">
        <div className="bg-slate-50 border-b border-slate-100 p-4 flex items-center justify-between">
          <div className="flex items-center gap-2 text-slate-500 text-sm font-medium">
            <FileText className="w-4 h-4" />
            brand_guide.md
          </div>
          <div className="flex items-center gap-1 text-emerald-600 text-xs font-bold uppercase tracking-wider">
            <CheckCircle2 className="w-3 h-3" />
            Generated by AI
          </div>
        </div>
        <div className="p-[var(--space-gap)] prose prose-slate max-w-none prose-headings:font-display prose-headings:text-slate-900 prose-p:text-slate-600 prose-li:text-slate-600">
          <ReactMarkdown>{guide}</ReactMarkdown>
        </div>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-[var(--space-gap)]">
        <div className="p-4 bg-brand-50 rounded-xl border border-brand-100 flex items-center gap-3">
          <div className="w-10 h-10 bg-brand-100 rounded-xl flex items-center justify-center text-brand-600 font-bold">1</div>
          <div className="text-sm font-medium text-brand-900">Consistent Strategy</div>
        </div>
        <div className="p-4 bg-brand-50 rounded-xl border border-brand-100 flex items-center gap-3">
          <div className="w-10 h-10 bg-brand-100 rounded-xl flex items-center justify-center text-brand-600 font-bold">2</div>
          <div className="text-sm font-medium text-brand-900">Visual Harmony</div>
        </div>
        <div className="p-4 bg-brand-50 rounded-xl border border-brand-100 flex items-center gap-3">
          <div className="w-10 h-10 bg-brand-100 rounded-xl flex items-center justify-center text-brand-600 font-bold">3</div>
          <div className="text-sm font-medium text-brand-900">Professional Handoff</div>
        </div>
      </div>
    </div>
  );
};
